project_id = "ojnikpihujkmcxvoaqdx"

[functions.validate-cnpj]
verify_jwt = false

[functions.validate-cep]
verify_jwt = false

[functions.send-to-autentique]
verify_jwt = false

[functions.sync-autentique-status]
verify_jwt = false

[functions.autentique-webhook]
verify_jwt = false
